// On the Edge Editor
// 
// Copyright © 2004-2021 Jukka Tykkyläinen
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software 
// and associated documentation files (the "Software"), to deal in the Software without 
// restriction, including without limitation the rights to use, copy, modify, merge, publish, 
// distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the 
// Software is furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all copies or 
// substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING 
// BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND 
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OtE Editor script.rc
//
#define IDC_TC_BROWSE_SCRIPT            3
#define IDC_CE_PLAYER_TERMINAL          3
#define IDC_TC_BROWSE_DIALOGUE          4
#define IDR_EDITOR_MENU                 101
#define IDD_NEWLEVEL                    102
#define IDD_SELECTION                   103
#define IDD_LEVEL_PROPERTIES            104
#define IDD_DYNAMIC_OBJECT              105
#define IDD_TILE                        106
#define IDD_STATIC_OBJECT               107
#define IDD_VESSEL                      108
#define IDD_SHIP                        109
#define IDD_ENEMY                       110
#define IDD_DIALOGUE_LINE               111
#define IDD_DIALOGUE                    112
#define IDD_GET_STRING                  113
#define IDD_TRIGGER                     114
#define IDD_PARTICLE_EFFECT             115
#define IDD_PARTICLE_EMITTER            115
#define IDD_GADGET                      116
#define IDD_GET_VECTOR                  117
#define IDD_GET_VECTOR4D                118
#define IDD_OBJECT_PROPERTIES           119
#define IDD_ABOUT                       120
#define IDD_CAMPAIGN_EDITOR             121
#define IDD_CAMPAIGN_BLOCK              122
#define IDD_AMMO                        123
#define IDD_PARTICLEEFFECT              124
#define IDD_SCRIPT                      125
#define IDD_SOUND                       126
#define IDD_EVENTACTION                 127
#define IDD_TERMINALCOMMAND             128
#define IDD_TERMINAL                    129
#define IDD_LIGHTEFFECT                 130
#define IDD_COMPONENT                   131
#define IDD_QUESTITEM                   132
#define IDD_SHIPPATCH                   133
#define IDD_TREE_SELECTION              134
#define IDD_SELECTCOLOR                 135
#define IDD_ASSISTANTMSG                136
#define IDC_SIZEX                       1000
#define IDC_SIZEY                       1001
#define ID_NEWLEVEL_OK                  1002
#define ID_NEWLEVEL_CANCEL              1003
#define IDC_SELECTION_LIST              1004
#define IDC_NEWLEVEL_HEIGHT             1004
#define ID_SELECTION_SELECT             1005
#define ID_NEWLEVEL_BROWSE              1005
#define ID_SELECTION_CANCEL             1006
#define ID_D_OK                         1006
#define ID_LP_OK                        1007
#define ID_SELECTION_SAVE               1007
#define ID_LP_CANCEL                    1008
#define ID_SELECTION_ADD                1008
#define ID_D_MOVE_DOWN                  1008
#define IDC_DO_NAME                     1009
#define ID_LP_SET_COLOR                 1009
#define ID_D_MOVE_UP                    1009
#define ID_SELECTION_IMPORT             1009
#define IDC_DO_MESH                     1010
#define ID_LP_SET_AMBIENT_COLOR         1010
#define ID_SELECTION_EXPORT             1010
#define IDC_DO_BROWSE_MESH              1011
#define ID_SELECTION_CLONE              1011
#define IDC_DO_HITPOINTS                1012
#define IDC_DO_BCCOEFFICIENT            1013
#define IDC_DO_MASS                     1014
#define IDC_DO_DRAGCOEFFICIENT          1015
#define IDC_DO_INDESTRUCTIBLE           1016
#define IDC_DO_GRAVITY                  1017
#define IDC_DO_DRAG                     1018
#define IDC_DO_COBJECTS                 1019
#define IDC_DO_CEXTERNAL                1020
#define IDC_DO_REQUIRESC                1021
#define ID_DO_CANCEL                    1022
#define ID_DO_OK                        1023
#define IDC_DO_REMOVE_MESH              1024
#define ID_TILE_OK                      1024
#define ID_TILE_CANCEL                  1025
#define IDC_DO_DROPWHENLOADED           1025
#define IDC_TILE_REMOVE_MESH            1026
#define IDC_DO_SUBCATEGORY              1026
#define IDC_TILE_BB                     1027
#define IDC_DO_DEFAULTPEFFECT           1027
#define IDC_TILE_RAMP                   1028
#define IDC_DO_BROWSE_DEFAULTPEFFECT    1028
#define IDC_TILE_NONE                   1029
#define IDC_DO_COLLISIONPARAM           1029
#define IDC_TILE_ACCURATE               1030
#define IDC_TILE_BROWSE_MESH            1031
#define IDC_TILE_MESH                   1032
#define IDC_TILE_NAME                   1033
#define IDC_SO_DEBRIS                   1034
#define IDC_TILE_CYLINDERCHECK          1034
#define IDC_SO_ENERGY_POD               1035
#define IDC_TILE_TEXTURE                1035
#define IDC_SO_REPAIR_POD               1036
#define IDC_TILE_BROWSE_TEXTURE         1036
#define IDC_SO_GADGET                   1037
#define IDC_TILE_REMOVE_TEXTURE         1037
#define IDC_SO_LEVEL_TELEPORT           1038
#define IDC_TILE_COLLISION_MESH         1038
#define IDC_SO_NORMAL_TELEPORT          1039
#define IDC_TILE_BROWSE_CMESH           1039
#define ID_SO_OK                        1040
#define IDC_TILE_REMOVE_CMESH           1040
#define ID_SO_CANCEL                    1041
#define IDC_TILE_SUBCATEGORY            1041
#define IDC_SO_NAME                     1042
#define IDC_TILE_HEIGHT_LEVEL           1042
#define IDC_SO_MESH                     1043
#define IDC_TILE_HEIGHT                 1043
#define IDC_SO_BROWSE_MESH              1044
#define IDC_TILE_SHAPE_PARAM            1044
#define IDC_SO_REMOVE_MESH              1045
#define IDC_SO_BVCOEFFICIENT            1046
#define IDC_SO_COBJECTS                 1047
#define IDC_SO_TARGET_ID                1048
#define IDC_SO_TARGET_ID_TEXT           1049
#define IDC_SO_BROWSE_TARGET            1050
#define IDC_SO_RECEIVING                1051
#define IDC_SO_DROPLOADED               1051
#define ID_VESSEL_CANCEL                1052
#define IDC_SO_TARGET_ID_TEXT2          1052
#define ID_VESSEL_OK                    1053
#define IDC_SO_ID                       1053
#define ID_VESSEL_DYNAMIC_OBJECT        1054
#define IDC_SO_CONTROLLER               1054
#define IDC_VESSEL_THRUST               1055
#define IDC_SO_BROWSE_PEFFECT           1055
#define IDC_VESSEL_LFORCE               1056
#define ID_SHIP_OK                      1056
#define IDC_SO_REMOVE_PEFFECT           1056
#define IDC_VESSEL_ZERO_DIST            1057
#define ID_SHIP_CANCEL                  1057
#define IDC_SO_GHOSTOBJECT              1057
#define IDC_VESSEL_LCOEF                1058
#define IDC_SHIP_ENERGY                 1058
#define IDC_SO_STARTPOS                 1058
#define IDC_VESSEL_TURN_SPEED           1059
#define IDC_SHIP_ENERGY_REG             1059
#define IDC_SO_PATCH                    1059
#define IDC_SHIP_MAX_LOAD               1060
#define IDC_VESSEL_EXP_DAMAGE           1060
#define IDC_SO_COMPONENT                1060
#define IDC_SHIP_BOOST_FORCE            1061
#define IDC_VESSEL_EXP_FORCE            1061
#define IDC_SO_QUESTITEM                1061
#define IDC_SHIP_BOOST_CON              1062
#define IDC_VESSEL_EXP_RADIUS           1062
#define IDC_SO_TARGET_ID_TEXT3          1062
#define ID_SHIP_VESSEL                  1063
#define IDC_VESSEL_EXP_EFFECT_ID        1063
#define IDC_SO_ALPHA                    1063
#define IDC_VESSEL_ENERGY               1063
#define ID_VESSEL_BROWSE_EFFECT         1064
#define ID_ENEMY_OK                     1064
#define IDC_VESSEL_ENERGY_REG           1064
#define ID_ENEMY_CANCEL                 1065
#define IDC_ENEMY_SHOOT_DIST            1066
#define IDC_ENEMY_MIN_DIST              1067
#define ID_ENEMY_VESSEL                 1068
#define IDC_ENEMY_REACTION_DIST         1069
#define IDC_ENEMY_MOBILE                1070
#define IDC_ENEMY_SUICIDAL              1071
#define IDC_LP_NAME                     1071
#define IDC_ENEMY_SHOOTS                1072
#define IDC_LP_DESCRIPTION              1072
#define IDC_ENEMY_EXPLODES              1073
#define IDC_LP_SINGLE_PLAYER            1073
#define IDC_ENEMY_GADGET                1074
#define IDC_LP_ENERGYPOD                1074
#define IDC_ENEMY_GADGET1               1074
#define ID_ENEMY_BROWSE_GADGET          1075
#define IDC_LP_REPAIRPOD                1075
#define ID_ENEMY_BROWSE_GADGET1         1075
#define IDC_LP_GRAVITY                  1076
#define IDC_ENEMY_BOLTED                1076
#define IDC_LP_DENSITY                  1077
#define IDC_ENEMY_CALLHELP              1077
#define IDC_LP_FRICTION                 1078
#define IDC_ENEMY_WAITANGLE             1078
#define IDC_ENEMY_AGGROMAINTAIN         1079
#define IDC_LP_X_DIR                    1080
#define IDC_ENEMY_HELP_DIST             1080
#define IDC_LP_Z_DIR                    1081
#define IDC_ENEMY_HELPFREQUENCY         1081
#define IDC_LP_EDIT_TOP                 1082
#define IDC_ENEMY_GADGET2               1082
#define IDC_LP_CMD_TOP                  1083
#define ID_ENEMY_BROWSE_GADGET2         1083
#define IDC_LP_EDIT_LEFT                1084
#define ID_DL_OK                        1084
#define IDC_ENEMY_TRIGGERPARAM1         1084
#define IDC_LP_CMD_LEFT                 1085
#define ID_DL_CANCEL                    1085
#define IDC_ENEMY_TRIGGERPARAM2         1085
#define IDC_LP_EDIT_FRONT               1086
#define IDC_DL_SPEAKER                  1086
#define IDC_ENEMY_TRIGGER_SCRIPT        1086
#define IDC_LP_CMD_FRONT                1087
#define IDC_DL_COMMENT                  1087
#define ID_ENEMY_BROWSE_TRIGGER_SCRIPT  1087
#define IDC_LP_EDIT_BOTTOM              1088
#define ID_D_DELETE                     1088
#define IDC_ENEMY_ONAGGRO_SCRIPT        1088
#define IDC_LP_CMD_BOTTOM               1089
#define ID_D_CANCEL                     1089
#define ID_ENEMY_BROWSE_ONAGGRO_SCRIPT  1089
#define IDC_LP_EDIT_RIGHT               1090
#define ID_D_EDIT                       1090
#define IDC_ENEMY_DAMAGE_COEF           1090
#define IDC_LP_CMD_RIGHT                1091
#define ID_D_ADD                        1091
#define IDC_LP_EDIT_BACK                1092
#define IDC_D_LIST                      1092
#define IDC_LP_CMD_BACK                 1093
#define IDC_D_NAME                      1093
#define ID_GS_OK                        1094
#define IDC_D_SCRIPT                    1094
#define ID_GS_CANCEL                    1095
#define IDC_D_BROWSE_SCRIPT             1095
#define IDC_GS_STRING                   1096
#define IDC_TRIGGER_DIALOGUE            1097
#define IDC_TRIGGER_REMOVE              1098
#define IDC_TRIGGER_CUSTOM              1099
#define IDC_TRIGGER_PLAYER              1100
#define IDC_TRIGGER_OPLAYER             1100
#define ID_TRIGGER_OK                   1101
#define ID_TRIGGER_CANCEL               1102
#define IDC_TRIGGER_ENEMY               1103
#define IDC_TRIGGER_OENEMY              1103
#define IDC_TRIGGER_DO                  1104
#define IDC_TRIGGER_ODO                 1104
#define IDC_TRIGGER_MULTITRIGGERING     1105
#define IDC_TRIGGER_TARGET              1106
#define IDC_TRIGGER_BROWSE              1107
#define IDC_TRIGGER_BROWSE_ACTION       1107
#define IDC_DO_ID                       1108
#define IDC_TRIGGER_OPOSSESSED          1108
#define ID_PE_OK                        1109
#define IDC_TRIGGER_OSPECIFIC           1109
#define ID_PE_CANCEL                    1110
#define IDC_TRIGGER_ID                  1110
#define ID_GADGET_OK                    1111
#define IDC_TRIGGER_SCRIPT              1111
#define IDC_TRIGGER_ACTIVE              1111
#define ID_GADGET_CANCEL                1112
#define IDC_TRIGGER_BROWSE_SCRIPT       1112
#define IDC_TRIGGER_SET_EFFECT          1112
#define IDC_VECTOR_X                    1113
#define IDC_TRIGGER_EFFECT_AT_OBJECT    1113
#define IDC_VECTOR_Y                    1114
#define IDC_PE_NAME                     1114
#define IDC_VECTOR_Z                    1115
#define IDC_PE_TEXTURE                  1115
#define IDC_PE_ID                       1116
#define IDC_VECTOR_W                    1116
#define IDC_PE_BROWSE_TEXTURE           1117
#define IDC_PE_MAX_PARTICLES            1118
#define IDC_PE_GRAVITY                  1119
#define IDC_PE_AUTOKILL                 1120
#define IDC_PE_HASMESH                  1120
#define IDC_PE_OBJECT_LIFETIME          1121
#define IDC_PE_START_DELAY              1121
#define IDC_PE_FREQUENCY                1122
#define IDC_PE_AUTOEMIT                 1123
#define IDC_PE_POSITION                 1124
#define IDC_PE_SIZE                     1125
#define IDC_PE_SIZE_START               1125
#define IDC_PE_POSITION_SPREAD          1126
#define IDC_PE_DIRECTION                1127
#define IDC_PE_DIRECTION_SPREAD         1128
#define IDC_PE_COLOR                    1129
#define IDC_PE_COLOR_START              1129
#define IDC_PE_COLOR_SPREAD             1130
#define IDC_PE_COLOR_END                1130
#define IDC_PE_SIZE_SPREAD              1131
#define IDC_PE_SIZE_END                 1131
#define IDC_PE_LIFETIME                 1132
#define IDC_PE_MINSPEED                 1132
#define IDC_PE_LIFETIME_SPREAD          1133
#define IDC_PE_MAXSPEED                 1133
#define IDC_PE_WEIGHT                   1134
#define IDC_PE_MINWEIGHT                1134
#define IDC_PE_WEIGHT_SPREAD            1135
#define IDC_PE_MAXWEIGHT                1135
#define IDC_PE_EMIT_COUNT               1136
#define IDC_PE_REMOVE_TEXTURE           1137
#define IDC_4D_X                        1137
#define IDC_4D_Y                        1138
#define IDC_PE_TTL                      1138
#define IDC_4D_Z                        1139
#define IDC_PE_INHERITSPEED             1139
#define IDC_4D_W                        1140
#define IDC_PE_BILLBOARD                1140
#define IDC_OP_TARGETID                 1141
#define IDC_PE_ADDITIVEBLEND            1141
#define IDC_OP_TARGETID_MSG             1142
#define IDC_PE_EXACTSPEED               1142
#define IDC_OP_BROWSE                   1143
#define IDC_PE_REPLACEOLD               1143
#define IDC_OP_BROWSE_TARGET            1143
#define IDC_OP_ID                       1144
#define IDC_GADGET_TYPE_WEAPON          1144
#define IDC_PE_GRAVITY_VECTOR           1144
#define IDC_GADGET_TYPE_KINETIC         1145
#define IDC_PE_EXTERNAL_GRAVITY         1145
#define IDC_OP_PEFFECT                  1145
#define IDC_GADGET_TYPE_HOVER           1146
#define IDC_PE_ROTMAT_ENABLED           1146
#define IDC_OP_BROWSE_PEFFECT           1146
#define IDC_GADGET_TYPE_REACTOR         1147
#define IDC_PE_INHERIT_ROTMAT           1147
#define IDC_GADGET_TYPE_MIND_CONTROL    1147
#define IDC_OP_LEFFECT2                 1147
#define IDC_GADGET_TYPE_SHIELD          1148
#define IDC_PE_ROTMAT_COUNT             1148
#define IDC_OP_BROWSE_LEFFECT           1148
#define IDC_GADGET_TYPE_ENGINE          1149
#define IDC_PE_SET_MIN_ROTMAT           1149
#define IDC_GADGET_TYPE_STEALTH         1149
#define IDC_OP_CONTROLLER               1149
#define IDC_GADGET_NAME                 1150
#define IDC_PE_SET_MAX_ROTMAT           1150
#define IDC_OP_BROWSE_CONTROLLER        1150
#define IDC_GADGET_ICON                 1151
#define IDC_OP_CPARAM1                  1151
#define IDC_GADGET_ID                   1152
#define IDC_OP_CPARAM2                  1152
#define IDC_GADGET_BROWSEICON           1153
#define IDC_OP_BROWSE_SCRIPT            1153
#define IDC_GADGET_REMOVEICON           1154
#define IDC_GADGET_PASSIVE              1155
#define IDC_GADGET_SOUND                1155
#define IDC_GADGET_CIRCULARLOAD         1156
#define IDC_GADGET_BROWSESOUND          1156
#define IDC_GADGET_LOADABLE             1157
#define IDC_GADGET_SCRIPT               1157
#define IDC_GADGET_LOAD_DAMAGE          1158
#define IDC_GADGET_BROWSESCRIPT         1158
#define IDC_GADGET_LOAD_AMMO            1159
#define IDC_GADGET_REMOVESOUND          1159
#define IDC_GADGET_LOADSPEED            1160
#define IDC_GADGET_REMOVESCRIPT         1160
#define IDC_GADGET_MASS                 1161
#define IDC_GADGET_WFORWARD             1162
#define IDC_GADGET_WFORWARDA            1163
#define IDC_GADGET_WNOVA                1164
#define IDC_GADGET_WNOVAA               1165
#define IDC_GADGET_WBACKWARD            1166
#define IDC_GADGET_WDAMAGE              1167
#define IDC_GADGET_WEXPRADIUS           1168
#define IDC_GADGET_WPEFFECT             1169
#define IDC_GADGET_HITPEFFECT           1169
#define IDC_GADGET_WBPEFFECT            1170
#define IDC_GADGET_HITSOUND             1170
#define IDC_GADGET_WBEXPLODES           1171
#define IDC_GADGET_WPEFFECTBROWSE       1172
#define IDC_GADGET_HITPEFFECTBROWSE     1172
#define IDC_GADGET_WSPEED               1173
#define IDC_GADGET_WANGLE               1174
#define IDC_GADGET_WLIFETIME            1175
#define IDC_GADGET_WEC                  1176
#define IDC_GADGET_WFIREPACE            1177
#define IDC_GADGET_WAMMOID              1178
#define IDC_GADGET_WBROWSEAMMO          1179
#define IDC_GADGET_WAMMOCOUNT           1180
#define IDC_GADGET_PFORCE               1181
#define IDC_GADGET_LOADENERGY           1182
#define IDC_GADGET_WBEXPLODES2          1182
#define IDC_GADGET_PANGLE               1183
#define IDC_CE_DELETEBLOCK              1183
#define IDC_GADGET_PRADIUS              1184
#define IDC_CE_BLOCKLIST                1184
#define IDC_GADGET_PEC                  1185
#define IDC_CE_NAME                     1185
#define IDC_GADGET_PFIREPACE            1186
#define IDC_CE_ADDBLOCK                 1186
#define IDC_GADGET_PPEFFECT             1187
#define IDC_CE_EDITBLOCK                1187
#define IDC_GADGET_PBROWSEPEFFECT       1188
#define IDC_CE_MOVEDOWN                 1188
#define IDC_GADGET_HEC                  1189
#define IDC_CE_MOVEUP                   1189
#define IDC_GADGET_HFORCE               1190
#define IDC_CE_GADGETLIST               1190
#define IDC_GADGET_HLOADINCREASE        1191
#define IDC_CE_ADDGADGET                1191
#define IDC_GADGET_WTHROWER             1191
#define IDC_GADGET_HPFORCE              1192
#define IDC_CE_REMOVEGADGET             1192
#define IDC_GADGET_WBEAM                1192
#define IDC_GADGET_EFORCE               1193
#define IDC_CE_EQUIPGADGET1             1193
#define IDC_GADGET_STEALTH_COEF         1193
#define IDC_CE_EQUIPGADGET              1193
#define IDC_GADGET_EBOOSTFORCE          1194
#define IDC_CE_EQUIPGADGET2             1194
#define IDC_GADGET_STEALTH_ENERGY       1194
#define IDC_GADGET_REXTRAENERGY         1195
#define IDC_CE_GADGET1                  1195
#define IDC_GADGET_POSEC                1195
#define IDC_GADGET_SDC                  1196
#define IDC_CE_GADGET2                  1196
#define IDC_CE_SHIPID                   1197
#define IDC_GADGET_MULTIPLAYER          1197
#define IDC_CE_BROWSESHIP               1198
#define IDC_GADGET_HITSOUNDBROWSE       1198
#define IDC_CE_FORCESHIP                1199
#define IDC_GADGET_HITSCRIPT            1199
#define IDC_CE_ENDMESSAGE               1200
#define IDC_GADGET_HITSCRIPTBROWSE      1200
#define IDC_CE_REMOVEGADGET1            1201
#define IDC_CB_LEVEL                    1201
#define IDC_GADGET_ONEUSE               1201
#define IDC_CE_REMOVEGADGET2            1202
#define IDC_CB_BROWSE                   1202
#define IDC_GADGET_SEC                  1202
#define IDC_CB_ALLDEAD                  1203
#define IDC_AMMO_PEFFECT                1203
#define IDC_GADGET_SPEFFECT             1203
#define IDC_CB_TARGETDEAD               1204
#define IDC_AMMO_BROWSEPEFFECT          1204
#define IDC_GADGET_SEFFECTBROWSE        1204
#define IDC_CB_TELEPORT                 1205
#define IDC_AMMO_NAME                   1205
#define IDC_GADGET_REXTRAENERGY2        1205
#define IDC_GADGET_POSDIST              1205
#define IDC_CB_SCRIPT                   1205
#define IDC_CB_TARGETID                 1206
#define IDC_AMMO_MASS                   1206
#define IDC_GADGET_POSRADIUS            1206
#define IDC_CB_MISSIONOBJECTIVES        1207
#define IDC_AMMO_ID                     1207
#define IDC_CB_SHOWOBJECTIVES           1208
#define IDC_AMMO_CONTROLLER             1208
#define IDC_AMMO_HASMESH                1209
#define IDC_AMMO_BROWSECONTROLLER       1209
#define IDC_CB_NONE                     1209
#define IDC_AMMO_HASPEFFECT             1210
#define IDC_AMMO_COLLIDESSTATIC         1210
#define IDC_CB_BROWSE_SCRIPT            1210
#define IDC_AMMO_GRAVITY                1211
#define IDC_AMMO_MESH                   1212
#define IDC_AMMO_BROWSEMESH             1213
#define IDC_TILE_PLATFORM               1214
#define IDC_AMMO_REMOVEMESH             1214
#define IDC_TILE_PLATFORMCORNER         1215
#define IDC_AMMO_REMOVEPEFFECT          1215
#define IDC_TILE_PLATFORMDCORNER        1216
#define IDC_DO_COLLISION_SPHERE         1216
#define IDC_AMMO_REMOVECONTROLLER       1216
#define IDC_TILE_PLATFORM2CORNER        1216
#define IDC_TILE_WALL                   1217
#define IDC_DO_COLLISION_CYLINDER       1217
#define IDC_TILE_WALLCORNER             1218
#define IDC_DO_COLLISION_BOX            1218
#define IDC_TILE_WALLDCORNER            1219
#define IDC_DO_EA_DEATH                 1219
#define IDC_TILE_CATWALKEND             1219
#define IDC_TILE_RAMPTYPE               1220
#define IDC_DO_EA_COLLISION             1220
#define IDC_AMMO_TYPE_ENERGY            1220
#define IDC_TILE_EMPTY                  1221
#define IDC_DO_EA_DAMAGE                1221
#define IDC_AMMO_TYPE_PLASMA            1221
#define IDC_SO_CUSTOMEA                 1221
#define IDC_TILE_OTHER                  1222
#define IDC_AMMO_TYPE_PROJECTILE        1222
#define IDC_VESSEL_ACCELERATE           1222
#define IDC_AMMO_TYPE_STUN              1223
#define IDC_VESSEL_BRAKE                1223
#define IDC_ENEMY_AGGRO_ATTACK          1223
#define IDC_TILE_PLATFORM2CORNERCROSS   1223
#define IDC_VESSEL_TURN                 1224
#define IDC_ENEMY_AGGRO_ESCAPE          1224
#define IDC_TILE_PLATFORM3CORNER        1224
#define IDC_AMMO_TYPE_KINETIC           1224
#define IDC_ENEMY_AGGRO_ROUTE           1225
#define IDC_TILE_PLATFORM4CORNER        1225
#define IDC_VESSEL_G2TRIGGER_ACTIVE     1226
#define IDC_TILE_CATWALK                1226
#define IDC_VESSEL_G2TRIGGER_HEALTH     1227
#define IDC_TILE_WALLBLOCK              1227
#define IDC_VESSEL_G2TRIGGER_DAMAGE     1228
#define IDC_TILE_HOLE                   1228
#define IDC_VESSEL_G2TRIGGER_AGGROTIME  1229
#define IDC_TILE_DUMMY                  1229
#define IDC_VESSEL_G2TRIGGER_SCRIPT     1230
#define IDC_VESSEL_DISABLE_G1           1231
#define IDC_VESSEL_DISPLAY_HEALTH       1232
#define IDC_VESSEL_POSSESSABLE          1233
#define IDC_VESSEL_TYPE_STUN2           1234
#define IDC_VESSEL_TYPE_ENERGY          1235
#define IDC_VESSEL_TYPE_PLASMA          1236
#define IDC_VESSEL_TYPE_PROJECTILE      1237
#define IDC_PEFFECT_CANCEL              1238
#define IDC_PEFFECT_SAVE                1239
#define IDC_PEFFECT_ADD                 1240
#define IDC_PEFFECT_EDIT                1241
#define IDC_PEFFECT_ID                  1242
#define IDC_PEFFECT_LIST                1243
#define IDC_PEFFECT_REMOVE              1244
#define IDC_PEFFECT_NAME                1245
#define IDC_PEFFECT_DURATION            1246
#define IDC_PEFFECT_AUTOKILL            1247
#define IDC_PE_SET_HANDLER              1248
#define IDC_PEFFECT_DURATION2           1248
#define IDC_PE_SET_INITIALIZER          1249
#define IDC_PE_LABEL_RESOURCE           1250
#define IDC_GADGET_DESCRIPTION          1252
#define IDC_SCRIPT_SCRIPT               1253
#define IDC_SCRIPT_NAME                 1254
#define IDC_SCRIPT_FILENAME             1255
#define IDC_SCRIPT_IMPORT               1256
#define IDC_SCRIPT_CANCEL               1257
#define IDC_SCRIPT_SAVE                 1258
#define IDC_SCRIPT_OUTPUT               1259
#define IDC_SCRIPT_VALIDATE             1260
#define IDC_SCRIPT_EXPORT               1261
#define IDC_SCRIPT_SAVEFILE             1262
#define IDC_SCRIPT_LOADTEXT             1263
#define IDC_SCRIPT_LOADBINARY           1264
#define IDC_SCRIPT_SELECTED             1265
#define IDC_SOUND_NAME                  1266
#define IDC_SOUND_FILENAME              1267
#define IDC_SOUND_BROWSE                1268
#define IDC_RADIO1                      1269
#define IDC_RADIO2                      1270
#define IDC_RADIO3                      1271
#define IDC_RADIO4                      1272
#define IDC_RADIO5                      1273
#define IDC_RADIO6                      1274
#define IDC_RADIO7                      1275
#define IDC_RADIO8                      1276
#define IDC_SOUND_LISTEN                1277
#define IDC_SOUND_VOLUME                1278
#define IDC_SOUND_ID                    1280
#define IDC_SOUND_STREAM                1281
#define IDC_AE_TXT1                     1282
#define IDC_AE_TXT2                     1283
#define IDC_AE_TXT3                     1284
#define IDC_AE_BROWSE1                  1285
#define IDC_AE_REMOVE1                  1286
#define IDC_NEWLEVEL_TILESET            1286
#define IDC_AE_BROWSE2                  1287
#define IDC_AE_REMOVE2                  1288
#define IDC_TC_NAME                     1288
#define IDC_AE_BROWSE3                  1289
#define IDC_TC_SCRIPT                   1289
#define IDC_AE_REMOVE3                  1290
#define IDC_TC_DIALOGUE                 1290
#define IDC_TC_VISIBLE                  1291
#define IDC_TC_ENABLED                  1292
#define IDC_TC_MESSAGE                  1296
#define IDC_TERMINAL_BUTTON1            1299
#define IDC_TERMINAL_BUTTON2            1300
#define IDC_TERMINAL_BUTTON3            1301
#define IDC_TERMINAL_BUTTON4            1302
#define IDC_TERMINAL_BUTTON5            1303
#define IDC_TERMINAL_BUTTON6            1304
#define IDC_TERMINAL_NAME               1305
#define IDC_TERMINAL_FUNCTIONAL         1306
#define IDC_TERMINAL_ONCLOSE            1307
#define IDC_TERMINAL_ID                 1308
#define IDC_TERMINAL_WELCOME            1309
#define IDC_TERMINAL_DISFUNCTIONAL      1310
#define IDC_TC_TRIGGER_SHUTDOWN         1311
#define IDC_TC_TRIGGER_NONE             1312
#define IDC_TC_TRIGGER_SCRIPT           1313
#define IDC_TC_TRIGGER_MESSAGE          1314
#define IDC_TC_TRIGGER_DIALOGUE         1315
#define IDC_D_UPDATE                    1316
#define IDC_D_OBJECTIVE                 1317
#define IDC_D_PRIORITY                  1318
#define IDC_TRIGGER_DELAY               1319
#define IDC_TRIGGER_TRIGGERING_ID       1320
#define IDC_TRIGGER_MESSAGE             1321
#define IDC_TRIGGER_TYPE_SCRIPT         1322
#define IDC_TRIGGER_TYPE_DIALOGUE       1323
#define IDC_TRIGGER_TYPE_TERMINAL       1324
#define IDC_TRIGGER_TYPE_MESSAGE        1325
#define IDC_LP_MUSIC1                   1326
#define IDC_LP_MUSIC2                   1327
#define IDC_TRIGGER_DAMAGE              1327
#define IDC_LP_BROWSEMUSIC1             1328
#define IDC_LP_BROWSEMUSIC2             1329
#define IDC_LP_MUSIC3                   1330
#define IDC_TRIGGER_TYPE_DAMAGE         1330
#define IDC_LP_BROWSEMUSIC3             1331
#define IDC_TRIGGER_TYPE_EFFECT         1331
#define IDC_LP_AUTOPLAY                 1332
#define IDC_LP_LOOP                     1333
#define IDC_LP_CAMERA_TYPE1             1334
#define IDC_LP_CAMERA_TYPE2             1335
#define IDC_LP_CAMERA_TYPE3             1336
#define IDC_LP_CAMERA_TYPE4             1337
#define IDC_LP_CAMERA_TYPE5             1338
#define IDC_LP_FORCE_CAMERA             1340
#define IDC_LP_SET_CAMERA_PARAM         1341
#define IDC_LE_RANGE1                   1343
#define IDC_LE_MIN_DURATION1            1344
#define IDC_LE_MAX_DURATION1            1345
#define IDC_LE_SET_COLOR1               1346
#define IDC_LE_SET_COLOR2               1347
#define IDC_LE_RANGE2                   1348
#define IDC_LE_MIN_DURATION2            1349
#define IDC_LE_MAX_DURATION2            1350
#define IDC_LE_NAME                     1351
#define IDC_LE_ID                       1352
#define IDC_LE_MINTRANS                 1353
#define IDC_LE_MAXTRANS                 1354
#define IDC_LE_STATE2_ENABLED           1355
#define IDC_ITEM_NAME                   1356
#define IDC_LE_ATTCOEF                  1356
#define IDC_ITEM_DESCRIPTION            1357
#define IDC_ITEM_ID                     1358
#define IDC_ITEM_ICON                   1359
#define IDC_COMPONENT_GADGET1           1360
#define IDC_PATCH_PARAM1                1360
#define IDC_ITEM_BROWSE                 1361
#define IDC_ITEM_remove                 1362
#define IDC_ITEM_REMOVE                 1362
#define IDC_COMPONENT_BROWSEGADGET1     1363
#define IDC_PATCH_TYPE1                 1363
#define IDC_COMPONENT_GADGET2           1364
#define IDC_PATCH_TYPE2                 1364
#define IDC_COMPONENT_BROWSEGADGET2     1365
#define IDC_PATCH_TYPE3                 1365
#define IDC_PATCH_TYPE4                 1366
#define IDC_PATCH_TYPE5                 1367
#define IDC_PATCH_TYPE6                 1368
#define IDC_OP_REFNAME                  1368
#define IDC_PATCH_PARAM2                1369
#define IDC_OP_SCRIPT                   1369
#define IDC_OP_EFFECT_POS               1370
#define IDC_OP_REQUIRES_UPDATE          1371
#define IDC_OP_OBJECTTYPE               1372
#define IDC_OP_SUBTYPE                  1373
#define IDC_OP_VISIBLE                  1374
#define IDC_OP_SCRIPTTYPE1              1375
#define IDC_OP_SCRIPTTYPE2              1376
#define IDC_OP_SCRIPTTYPE3              1377
#define IDC_OP_SCRIPTTYPE4              1378
#define IDC_OP_SCRIPTTYPE5              1379
#define IDC_OP_SCRIPTTYPE6              1380
#define IDC_OP_SCRIPT_MSG               1381
#define IDC_CB_SCRIPT_NAME              1382
#define IDC_TREE1                       1383
#define IDC_GADGET_ENEMY                1385
#define IDC_DO_DEFAULT_EFFECT_POS       1386
#define IDC_SO_DEFAULT_EFFECT_POS       1387
#define IDC_PE_TYPE_EXP                 1389
#define IDC_PE_TYPE_ENGINE              1391
#define IDC_PE_TYPE_ENV                 1392
#define IDC_PE_TYPE_SPECIAL             1393
#define IDC_PE_TYPE_OTHER               1394
#define IDC_PE_TYPE_AMMO                1395
#define IDC_PE_TYPE_WEAPON              1396
#define IDC_PE_OTHER_EFFECT             1397
#define IDC_SC_PICK                     1398
#define IDC_SC_A                        1399
#define IDC_SC_R                        1400
#define IDC_SC_G                        1401
#define IDC_SC_B                        1402
#define IDC_ENEMY_AI_DONT_FOLLOW        1403
#define IDC_ENEMY_AI_CONTINUE           1404
#define IDC_TILE_SELECT_DYNAMIC         1405
#define IDC_ENEMY_AI_DISABLE_PATHFINDING 1405
#define IDC_TILE_SELECT_STATIC          1406
#define IDC_ENEMY_AI_USE_CUSTOM_ROUTE   1406
#define IDC_TILE_SELECT_ENEMY           1407
#define IDC_GADGET_LBLSPEED             1407
#define IDC_TILE_SELECT_GADGET          1408
#define IDC_GADGET_LBLAMMOID            1408
#define IDC_TILE_SELECT_PATCH           1409
#define IDC_TILE_SELECT_COMPONENT       1410
#define IDC_TILE_SELECT_QUESTITEM       1411
#define IDC_TILE_SELECT_PEFFECT         1412
#define IDC_TILE_SELECT_LEFFECT         1413
#define IDC_TILE_SELECT_SOUND           1414
#define IDC_TILE_SELECT_GLOBAL_SCRIPT   1415
#define IDC_TILE_SELECT_LOCAL_SCRIPT    1416
#define IDC_TILE_SELECT_DIALOGUE        1417
#define IDC_TILE_SELECT_TERMINAL        1418
#define IDC_TILE_SELECT_ROUTE           1419
#define IDC_SCRIPT_CONFIRM              1420
#define IDC_TILE_SELECT_CONTROLLER      1421
#define IDC_VESSEL_AMMOSPAWN            1422
#define IDC_TILE_SELECT_ASSISTANTMSG    1422
#define IDC_AM_MSG                      1423
#define IDC_AM_ID                       1424
#define IDC_CHECK1                      1425
#define IDC_ENEMY_AI_ANTICIPATE         1425
#define ID__FILE                        40001
#define ID_FILE_SAVEAS                  40004
#define ID_FILE_QUIT                    40005
#define ID_EDIT_LEVELPROPERTIES         40006
#define ID_INSERT_SHIP                  40007
#define ID_INSERT_PLAYER1               40007
#define ID_INSERT_ENEMY                 40008
#define ID_INSERT_DYNAMICOBJECT         40009
#define ID_INSERT_STATICOBJECT          40010
#define ID_INSERT_TRIGGER               40011
#define ID_INSERT_WAYPOINTSET           40012
#define ID_DATABASE_SHIPS               40013
#define ID_DATABASE_ENEMIES             40014
#define ID_DATABASE_DYNAMICOBJECTS      40015
#define ID_DATABASE_STATICOBJECTS       40016
#define ID_DATABASE_PROJECTILES         40017
#define ID_DATABASE_EFFECTS             40017
#define ID_DATABASE_GADGETS             40018
#define ID_DATABASE_TILESET             40019
#define ID_INSERT_DIALOGUE              40020
#define ID_FILE_OPEN_LEVEL              40021
#define ID_FILE_SAVE_LEVEL              40022
#define ID_FILE_CLOSE_LEVEL             40024
#define ID_FILE_NEW_LEVEL               40026
#define ID_EDIT_TILEEDITMODE            40027
#define ID_EDIT_SELECTTILE              40028
#define ID_EDIT_DIALOGUES               40030
#define ID_EDIT_OBJECTPROPERTIES        40031
#define ID_EDIT_REPAIR                  40032
#define ID_EDIT_WAYPOINTS               40033
#define ID_EDIT_DELETEOBJECT            40034
#define ID_EDIT_SHOWTRIGGERS            40035
#define ID_DELETE_ALL_OBJECTS           40036
#define ID_EDIT_CAMPAIGN_EDITOR         40037
#define ID_ABOUT                        40038
#define ID_DATABASE_AMMOS               40039
#define ID_DATABASE_GLOBALSCRIPTS       40040
#define ID_DATABASE_SOUNDS              40041
#define ID_EDIT_LEVELSCRIPTS            40042
#define ID_DATABASE_CREATETILESET       40043
#define ID_EDIT_AUTOTRIM                40044
#define ID_EDIT_TERMINALS               40045
#define ID_DATABASE_LIGHTEFFECTS        40046
#define ID_DATABASE_COMPONENTS          40048
#define ID_DATABASE_QUESTITEMS          40049
#define ID_DATABASE_SHIPPATCHES         40050
#define ID_EDIT_RANDOMIZEAUTOTRIM       40051
#define ID_EDIT_RESETCAMERAPOSITION     40052
#define ID_EDIT_RAPIDTILEELEVATION      40053
#define ID_EDIT_ASSISTANTMESSAGES       40054

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         40055
#define _APS_NEXT_CONTROL_VALUE         1426
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
